# Generated by Django 6.0.3 on 2026-03-10 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_audio', models.FileField(upload_to='uploads/originals/')),
                ('watermarked_audio', models.FileField(blank=True, null=True, upload_to='uploads/watermarked/')),
                ('watermark_data', models.CharField(help_text='Текст або ідентифікатор водяного знаку', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
