# Generated by Django 6.0.3 on 2026-03-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='algorithm',
            field=models.CharField(default='dwt_svd', max_length=50),
        ),
    ]
