# Generated by Django 6.0.3 on 2026-05-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark_api', '0002_audiotrack_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='ber',
            field=models.FloatField(blank=True, help_text='Коефіцієнт бітових помилок', null=True),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='ncc',
            field=models.FloatField(blank=True, help_text='Нормалізована кореляція', null=True),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='psnr',
            field=models.FloatField(blank=True, help_text='Пікове відношення сигнал/шум', null=True),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='snr',
            field=models.FloatField(blank=True, help_text='Відношення сигнал/шум', null=True),
        ),
    ]
