# Generated by Django 6.0.3 on 2026-05-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark_api', '0003_audiotrack_ber_audiotrack_ncc_audiotrack_psnr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='ecc_type',
            field=models.CharField(blank=True, help_text='Тип кодування (Hamming / Reed-Solomon)', max_length=50, null=True),
        ),
    ]
