# Generated by Django 6.0.3 on 2026-05-06 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark_api', '0004_audiotrack_ecc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiotrack',
            name='ber',
        ),
        migrations.RemoveField(
            model_name='audiotrack',
            name='ecc_type',
        ),
        migrations.RemoveField(
            model_name='audiotrack',
            name='ncc',
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='is_ecc',
            field=models.BooleanField(default=False, help_text='Чи активовано захист ECC'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='psnr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='snr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExpertiseResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attack_type', models.CharField(max_length=100)),
                ('attack_params', models.CharField(max_length=100)),
                ('extracted_text', models.TextField()),
                ('ber', models.FloatField()),
                ('ncc', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='watermark_api.audiotrack')),
            ],
        ),
    ]
