# Generated by Django 6.0.3 on 2026-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermark_api', '0005_remove_audiotrack_ber_remove_audiotrack_ecc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertiseresult',
            name='psnr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertiseresult',
            name='snr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
